server:
  port: 9999
  contextPath: /uaa
# config registry eureka
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost/auth
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

security:
  sessions: if-required
  user:
    password: password

  oauth2:
      client:
        clientId: client
        clientSecret: secret
        authorized-grant-types: authorization_code,refresh_token,password
        scope: openid

